In [15]:
import requests 

docs_url = 'https://github.com/alexeygrigorev/llm-rag-workshop/raw/main/notebooks/documents.json'
docs_response = requests.get(docs_url)
documents_raw = docs_response.json()

documents = []

for course in documents_raw:
    course_name = course['course']

    for doc in course['documents']:
        doc['course'] = course_name
        documents.append(doc)

In [16]:
documents[2]

{'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
 'section': 'General course-related questions',
 'question': 'Course - Can I still join the course after the start date?',
 'course': 'data-engineering-zoomcamp'}

In [17]:
import pandas as pd

df = pd.DataFrame(documents, columns=['course', 'section', 'question', 'text'])

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
cv = CountVectorizer(min_df=5)

In [20]:
cv.fit(df.text)

CountVectorizer(min_df=5)

In [21]:
cv.get_feature_names_out()

array(['01', '02', '03', ..., 'youtube', 'zip', 'zoomcamp'],
      shape=(1524,), dtype=object)

In [22]:
docs_example = [
    "Course starts on 15th Jan 2024",
    "Prerequisites listed on GitHub",
    "Submit homeworks after start date",
    "Registration not required for participation",
    "Setup Google Cloud and Python before course"
]

In [23]:
cv = CountVectorizer(stop_words='english')

In [24]:
cv.fit(docs_example)

CountVectorizer(stop_words='english')

In [25]:
cv.get_feature_names_out()

array(['15th', '2024', 'cloud', 'course', 'date', 'github', 'google',
       'homeworks', 'jan', 'listed', 'participation', 'prerequisites',
       'python', 'registration', 'required', 'setup', 'start', 'starts',
       'submit'], dtype=object)

In [26]:
X = cv.transform(docs_example)

In [27]:
pd.DataFrame(X.todense(), columns=cv.get_feature_names_out()).T

0  1  2  3  4
15th           1  0  0  0  0
2024           1  0  0  0  0
cloud          0  0  0  0  1
course         1  0  0  0  1
date           0  0  1  0  0
github         0  1  0  0  0
google         0  0  0  0  1
homeworks      0  0  1  0  0
jan            1  0  0  0  0
listed         0  1  0  0  0
participation  0  0  0  1  0
prerequisites  0  1  0  0  0
python         0  0  0  0  1
registration   0  0  0  1  0
required       0  0  0  1  0
setup          0  0  0  0  1
start          0  0  1  0  0
starts         1  0  0  0  0
submit         0  0  1  0  0

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv = TfidfVectorizer(stop_words='english', min_df=5)
X = cv.fit_transform(df.text)

names = cv.get_feature_names_out()

df_docs = pd.DataFrame(X.toarray(), columns=names)
df_docs.round(2)

01   02   03   04   05   06   09   10  100   11  ...  y_val  yaml  year  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.00   0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.00   0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.00   0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.00   0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.00   0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...   ...   ...   
943  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.00   0.0   
944  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.00   0.0   
945  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.17   0.0   
946  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.00   0.0   
947  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0  0.00   0.0   

     yellow  yellow_tripdata_2021   yes   yml  youtube  zip  zoomcamp  
0       0.0                   0.0  0.00  0.00      0.0  0.0      0.00  
1       0.0                   0.0  0.00  0.00      0.0  0.0      0.43  
2       0.0                   0.0  0.28  0.00      0.0  0.0      0.00  
3       0.0                   0.0  0.00  0.00      0.0  0.0      0.00  
4       0.0                   0.0  0.00  0.00      0.0  0.0      0.00  
..      ...                   ...   ...   ...      ...  ...       ...  
943     0.0                   0.0  0.00  0.11      0.0  0.0      0.00  
944     0.0                   0.0  0.00  0.00      0.0  0.0      0.00  
945     0.0                   0.0  0.00  0.00      0.0  0.0      0.00  
946     0.0                   0.0  0.00  0.00      0.0  0.0      0.00  
947     0.0                   0.0  0.00  0.00      0.0  0.0      0.15  

[948 rows x 1333 columns]

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv = TfidfVectorizer(stop_words='english', min_df=5)
X = cv.fit_transform(df.text)

In [30]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 23808 stored elements and shape (948, 1333)>

In [31]:
query = "Do I need to know python to sign up for the January course?"

q = cv.transform([query]) 
q.toarray()

array([[0., 0., 0., ..., 0., 0., 0.]], shape=(1, 1333))

In [53]:
from sklearn.metrics.pairwise import cosine_similarity

In [33]:
score = cosine_similarity(X, q).flatten()

In [34]:
import numpy as np

In [35]:
np.argsort(score) #con esto le damos ranking a cada documento por sus índices) El doc que aparece primero es el que tiene más score (puntuación más alta.
# El primero que aparece es el que tiene la puntuación más baja.

array([718, 699, 700, 701, 703, 704, 707, 710, 711, 712, 717, 698, 476,
       477, 478, 479, 480, 481, 482, 483, 486, 487, 833, 820, 821, 822,
       823, 824, 825, 827, 828, 830, 832, 488, 834, 467, 468, 471, 472,
       473, 474, 475, 697, 526, 514, 515, 516, 517, 518, 519, 520, 523,
       524, 525, 513, 527, 528, 530, 532, 533, 534, 535, 536, 537, 538,
       499, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 819, 501,
       504, 505, 506, 507, 508, 509, 510, 512, 864, 386, 851, 853, 854,
       855, 859, 860, 861, 862, 863, 385, 865, 387, 389, 390, 392, 397,
       399, 400, 402, 404, 369, 358, 359, 360, 361, 362, 363,  32, 366,
       367, 368, 405, 370, 371, 376, 377, 379, 380, 382, 383, 384, 442,
       839, 840, 841, 843, 846, 847, 848, 850, 437, 441, 836, 443, 444,
       447, 453, 460, 461, 462, 463, 466, 420, 407, 408, 409, 410, 412,
       414, 416, 417, 418, 419, 542, 421, 422, 423, 426, 427, 428, 429,
       430, 432, 654, 643, 644, 645, 646, 647, 649, 650, 651, 65

In [36]:
np.argsort(score) [-5:] #tomamos los más altos valores

array([764,  27, 806, 577, 445])

In [37]:
fields = ['section', 'question', 'text']

In [45]:
matrices = {}
vectorizers = {}
for f in fields:
    cv = TfidfVectorizer(stop_words='english', min_df=5)
    X = cv.fit_transform(df[f])
    matrices[f] = X
    vectorizers [f] = cv



In [46]:
vectorizers

{'section': TfidfVectorizer(min_df=5, stop_words='english'),
 'question': TfidfVectorizer(min_df=5, stop_words='english'),
 'text': TfidfVectorizer(min_df=5, stop_words='english')}

In [40]:
n = len(df)

In [41]:
import numpy as np


In [76]:
score =  np.zeros (n)

query = "I just discovered the course, is it too late to join?"

boosts = {
    'question': 3
    #'text': 0.5
}

for f in fields: 
    q = vectorizers[f].transform([query])
    x = matrices[f] 

    f_score = cosine_similarity(x, q).flatten() 

    boots = boosts.get(f, 1.0)

    score = score + boots * f_score 

In [77]:
filters = {
    'course': 'data-engineering-zoomcamp'
}

In [78]:
for field, value in filters.items():
    mask = (df[field] == value).astype(int)
    score = score * mask

In [82]:
idx = np.argsort(-score)[:5]

In [83]:
df.iloc[idx]

course                           section  \
7   data-engineering-zoomcamp  General course-related questions   
0   data-engineering-zoomcamp  General course-related questions   
34  data-engineering-zoomcamp  General course-related questions   
1   data-engineering-zoomcamp  General course-related questions   
9   data-engineering-zoomcamp  General course-related questions   

                                             question  \
7   Course - Can I follow the course after it fini...   
0                Course - When will the course start?   
34               How can we contribute to the course?   
1   Course - What are the prerequisites for this c...   
9   Course - Which playlist on YouTube should I re...   

                                                 text  
7   Yes, we will keep all the materials after the ...  
0   The purpose of this document is to capture fre...  
34  Star the repo! Share it with friends if you fi...  
1   GitHub - DataTalksClub data-engineering-zoomca...  
9   All the main videos are stored in the Main “DA...

In [84]:
class TextSearch:

    def __init__(self, text_fields):
        self.text_fields = text_fields
        self.matrices = {}
        self.vectorizers = {}

    def fit(self, records, vectorizer_params={}):
        self.df = pd.DataFrame(records)

        for f in self.text_fields:
            cv = TfidfVectorizer(**vectorizer_params)
            X = cv.fit_transform(self.df[f])
            self.matrices[f] = X
            self.vectorizers[f] = cv

    def search(self, query, n_results=10, boost={}, filters={}):
        score = np.zeros(len(self.df))

        for f in self.text_fields:
            b = boost.get(f, 1.0)
            q = self.vectorizers[f].transform([query])
            s = cosine_similarity(self.matrices[f], q).flatten()
            score = score + b * s

        for field, value in filters.items():
            mask = (self.df[field] == value).values
            score = score * mask

        idx = np.argsort(-score)[:n_results]
        results = self.df.iloc[idx]
        return results.to_dict(orient='records')

In [85]:
index = TextSearch(
    text_fields=['section', 'question', 'text']
)
index.fit(documents)

index.search(
    query='I just signed up. Is it too late to join the course?',
    n_results=5,
    boost={'question': 3.0},
    filters={'course': 'data-engineering-zoomcamp'}
)

[{'text': "Yes, even if you don't register, you're still eligible to submit the homeworks.\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything for the last minute.",
  'section': 'General course-related questions',
  'question': 'Course - Can I still join the course after the start date?',
  'course': 'data-engineering-zoomcamp'},
 {'text': "The purpose of this document is to capture frequently asked technical questions\nThe exact day and hour of the course will be 15th Jan 2024 at 17h00. The course will start with the first  “Office Hours'' live.1\nSubscribe to course public Google Calendar (it works from Desktop only).\nRegister before the course starts using this link.\nJoin the course Telegram channel with announcements.\nDon’t forget to register in DataTalks.Club's Slack and join the channel.",
  'section': 'General course-related questions',
  'question': 'Course - When will the course start?',
  'course': 'data-engineerin

In [104]:
from sklearn.decomposition import TruncatedSVD

X = matrices['text']
cv = vectorizers['text']

svd = TruncatedSVD(n_components=16)
X_emb = svd.fit_transform(X)

X_emb[0]

array([ 0.09653174, -0.08198689, -0.10300345, -0.08024181,  0.06876766,
       -0.06141254,  0.01374544, -0.1545658 ,  0.24699962,  0.26808468,
        0.08152856,  0.07309585, -0.09119782,  0.0729624 , -0.00110628,
        0.00386672])

In [105]:
X_emb.shape

(948, 16)

In [106]:
X_emb[0]

array([ 0.09653174, -0.08198689, -0.10300345, -0.08024181,  0.06876766,
       -0.06141254,  0.01374544, -0.1545658 ,  0.24699962,  0.26808468,
        0.08152856,  0.07309585, -0.09119782,  0.0729624 , -0.00110628,
        0.00386672])

In [107]:
query = 'I just signed up. Is it too late to join the course?'

Q = cv.transform([query])
Q_emb = svd.transform(Q)
Q_emb[0]

array([ 0.05790283, -0.03846077, -0.05708439, -0.02880167,  0.03992503,
       -0.06243425,  0.00465172, -0.10228332,  0.1654968 ,  0.17770133,
        0.06465213,  0.06552701, -0.07017054,  0.06033649,  0.01678947,
        0.00097987])

In [108]:
np.dot(X_emb[0], Q_emb[0])

np.float64(0.14875127576419722)

In [109]:
score = cosine_similarity(X_emb, Q_emb).flatten()
idx = np.argsort(-score)[:10]
df.loc[idx]

course                           section  \
764  machine-learning-zoomcamp   Projects (Midterm and Capstone)   
449  machine-learning-zoomcamp  General course-related questions   
0    data-engineering-zoomcamp  General course-related questions   
814             mlops-zoomcamp        +-General course questions   
451  machine-learning-zoomcamp  General course-related questions   
11   data-engineering-zoomcamp  General course-related questions   
7    data-engineering-zoomcamp  General course-related questions   
450  machine-learning-zoomcamp  General course-related questions   
2    data-engineering-zoomcamp  General course-related questions   
15   data-engineering-zoomcamp  General course-related questions   

                                              question  \
764  What If I submitted only two projects and fail...   
449  The course has already started. Can I still jo...   
0                 Course - When will the course start?   
814  What if my answer is not exactly the same as t...   
451      Can I submit the homework after the due date?   
11   Certificate - Can I follow the course in a sel...   
7    Course - Can I follow the course after it fini...   
450                When does the next iteration start?   
2    Course - Can I still join the course after the...   
15   Homework - Are late submissions of homework al...   

                                                  text  
764  If you have submitted two projects (and peer-r...  
449  Yes, you can. You won’t be able to submit some...  
0    The purpose of this document is to capture fre...  
814  Please choose the closest one to your answer. ...  
451  No, it’s not possible. The form is closed afte...  
11   No, you can only get a certificate if you fini...  
7    Yes, we will keep all the materials after the ...  
450  The course is available in the self-paced mode...  
2    Yes, even if you don't register, you're still ...  
15   No, late submissions are not allowed. But if t...

In [110]:
from sklearn.decomposition import NMF
nmf = NMF(n_components=16)
X_emb = nmf.fit_transform(X)
X_emb[0]

array([0.12781764, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.00062404, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

In [111]:
Q = cv.transform([query])
Q_emb = nmf.transform(Q)
Q_emb[0]


array([0.08494786, 0.00240809, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.0021045 , 0.        ,
       0.        ])

In [113]:
score = cosine_similarity(X_emb, Q_emb).flatten()
idx = np.argsort(-score)[:10]
df.loc[idx]

course                           section  \
2    data-engineering-zoomcamp  General course-related questions   
449  machine-learning-zoomcamp  General course-related questions   
814             mlops-zoomcamp        +-General course questions   
11   data-engineering-zoomcamp  General course-related questions   
0    data-engineering-zoomcamp  General course-related questions   
764  machine-learning-zoomcamp   Projects (Midterm and Capstone)   
7    data-engineering-zoomcamp  General course-related questions   
451  machine-learning-zoomcamp  General course-related questions   
436  machine-learning-zoomcamp  General course-related questions   
450  machine-learning-zoomcamp  General course-related questions   

                                              question  \
2    Course - Can I still join the course after the...   
449  The course has already started. Can I still jo...   
814  What if my answer is not exactly the same as t...   
11   Certificate - Can I follow the course in a sel...   
0                 Course - When will the course start?   
764  What If I submitted only two projects and fail...   
7    Course - Can I follow the course after it fini...   
451      Can I submit the homework after the due date?   
436                      Is it going to be live? When?   
450                When does the next iteration start?   

                                                  text  
2    Yes, even if you don't register, you're still ...  
449  Yes, you can. You won’t be able to submit some...  
814  Please choose the closest one to your answer. ...  
11   No, you can only get a certificate if you fini...  
0    The purpose of this document is to capture fre...  
764  If you have submitted two projects (and peer-r...  
7    Yes, we will keep all the materials after the ...  
451  No, it’s not possible. The form is closed afte...  
436  The course videos are pre-recorded, you can st...  
450  The course is available in the self-paced mode...

In [114]:
import torch
from transformers import BertModel, BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("bert-base-uncased")
model.eval()  # Set the model to evaluation mode if not training

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

In [116]:
texts = [
    "Yes, we will keep all the materials after the course finishes.",
    "You can follow the course at your own pace after it finishes"
]
encoded_input = tokenizer(texts, padding=True, truncation=True, return_tensors='pt')
encoded_input

{'input_ids': tensor([[  101,  2748,  1010,  2057,  2097,  2562,  2035,  1996,  4475,  2044,
          1996,  2607, 12321,  1012,   102],
        [  101,  2017,  2064,  3582,  1996,  2607,  2012,  2115,  2219,  6393,
          2044,  2009, 12321,   102,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]])}

In [117]:
with torch.no_grad():  # Disable gradient calculation for inference
    outputs = model(**encoded_input)
    hidden_states = outputs.last_hidden_state

In [121]:
hidden_states[0]

tensor([[ 0.1010,  0.0181,  0.1303,  ..., -0.2932,  0.1863,  0.6615],
        [ 1.0608, -0.1242,  0.1370,  ..., -0.1605,  1.0429,  0.3532],
        [ 0.1802,  0.0776,  0.3941,  ..., -0.1379,  0.5974,  0.1704],
        ...,
        [ 0.4738, -0.0184,  0.2186,  ..., -0.0013, -0.0833, -0.2170],
        [ 0.6516,  0.1216, -0.2494,  ...,  0.1557, -0.5632, -0.4310],
        [ 0.7164,  0.2157, -0.0281,  ...,  0.2281, -0.6725, -0.3245]])

In [122]:
sentence_embeddings = hidden_states.mean(dim=1)
sentence_embeddings.shape

torch.Size([2, 768])

In [123]:
sentence_embeddings

tensor([[ 0.3600, -0.1607,  0.3545,  ...,  0.0429,  0.0348, -0.0382],
        [ 0.1785, -0.5000,  0.2528,  ..., -0.1141, -0.3361,  0.4110]])